apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: realworld-msa
build:
  artifacts:
    - image: realworld-msa/auth-service
      context: microservices/auth-service
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - "k8s/**/*.yaml"
portForward:
  - resourceType: service
    resourceName: auth-service
    port: 9000
